### PR TITLE
add erwa as dep

### PR DESCRIPTION
**Pull request by comtihon**
add erwa as ordinary dep (not test) as it is used in project.
Run autoformatting and refactored `awre_transport:init/1` to make IDE search&refactoring search transport implementations.
No logic changes.

### CODE REVIEW

**Comment by bwegh** [comment]
why do you want to add erwa as a dep? you could implement a pure client application without erwa.

**Comment by comtihon** [comment]
erwa is called from `awre_trans_tcp` and `awre_trans_local`. Wihout it's dep project won't compile.

**Comment by bwegh** [comment]
yes, awre_tran_local is for local connections with a local running erwa router.
but then and only then erwa is needed, yet not when going there by using TCP.

**Comment by bwegh** [comment]
just double checked, it is not used in erwa_trans_tcp

**Comment by comtihon** [comment]
sorry, its my mistake, yes, really - erwa is used only in `awre_trans_local`.
And it compiles, even without erwa dep.
But IDE always complains on non-existent module, so I added the dep.

**Comment by bwegh** [comment]
I will move awre_local directly to erwa, so implementing functions and events directly in the router will be way easier.

**Pull request closed without merging**
